openapi: 3.1.0
info:
  version: 1.0.0
  title: My contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This application provides functionality to manage contacts and user authentication.
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://hw3-crud-5.onrender.com/
  - url: https://contacts-app-3lrz.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
# openapi: 3.1.0
# info:
#   version: 1.0.0
#   title: <назва вашого додатку>
#   license:
#     name: Apache 2.0
#     url: http://www.apache.org/licenses/LICENSE-2.0.html
#   description: <опис вашого додатку>
# tags:
#   # теги, що ви будете використовувати
# servers:
#   - url: http://localhost:3000
#   - url: #посилання на задеплоєний сайт
# paths:
#   # тут будуть посилання на ендпоінти
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
